name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Load Composer cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Run a docker-compose
      run: docker-compose up -d

    - name: Install composer dependencies
      run: docker-compose exec -T web composer install

    - name: Run a CS check
      run: docker-compose exec -T web composer cs-check

    - name: Run a PhpStan
      run: docker-compose exec -T web composer phpstan

    - name: Run unit tests
      run: docker-compose exec -T web composer test

    - name: Configure swoole serve
      run: cp config/autoload/swool.local.php.dist config/autoload/swool.local.php

    - name: Run swoole server
      run: docker-compose exec -T -d web composer serve

    - name: Run codeception tests
      run: docker-compose exec -T web composer codeception
